### ISSUE TITLE
Example: how to use docx_extract_tbl() with lapply() 

### ISSUE THREAD

**Issue by DavoOZ** [hrbrmstr/docxtractr#3]
Fantastic new package - thankyou.
In the examples please show how to wrap docx_extract_tbl() with lapply() to access all the tables in a document in one hit.

**Comment by hrbrmstr** [comment]
roger that. will do so between tonight & tomorrow

**Comment by hrbrmstr** [comment]
take a look at the latest version (0.1.0.9000) I just pushed. it has two new functions, one of which is to extract all the tables in a document and another to help with cleaning up column names in scraped tables. There are examples in the R help and also in the new README.

**Comment by DavoOZ** [comment]
Wow - that was a rapid response and it works like a charm!

**Comment by zoe-xanthellae** [comment]
Building off of your creation of mcga, is there a way to run this using lapply on dataframe elements listed within a list? For example, I am using lapply along with function (fileName) to go into a folder, read in all docx files (4 for now, eventually 50+), and extract all tables from those documents, putting it into a list as here:

    tables <- lapply(list.files(path = "./files", pattern = ".docx", full.names = TRUE), function(fileName){
      temp <- docxtractr::read_docx(paste(fileName, sep = "/"))
      temp1 <- docxtractr::docx_extract_all_tbls(temp, guess_header = TRUE, trim = TRUE)
      return(temp1)
    })

Now, this creates a nice list of lists, *but*:
a) some documents do not have tables (list length = 0), while others have one or more 
b) some tables don't have "guessable" headers since they have empty upper-left-corner cells (found this out through using docx_describe_tbls()
c) some headers aren't syntactically correct (thus flextable won't knit them using pandoc/rmarkdown when looking for col_keys), but this is where mcga comes in

Any suggestions for applying mcga to dataframes (fix problem c) that are in listed in lists of a list, while accounting for those tables coming in that docx_extract_all_tbls doesn't guess the headers (problem b)? I apologize if any of this wording is confusing, somewhat of a R novice, happy to elaborate where I can!

**Comment by hrbrmstr** [comment]
Hey @zoe-xanthellae. I think I can whip up something, but if you had ~3 docs that you could zip up and add upload here I could return with an example a bit quicker.

**Comment by zoe-xanthellae** [comment]
Hey @hrbrmstr . Great, thank you! Sorry for the delayed reply, crunch time on a project last week. Here's a folder with three docs: one with no tables, and the other two have 1-2 tables with different column header formatting.
[TablesExample.zip](https://github.com/hrbrmstr/docxtractr/files/1869726/TablesExample.zip)
